language: php

matrix:
  fast_finish: true
  include:
    - php: 7.2
    - php: 7.3

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

services:
  - memcached
  - redis-server
  - mysql

before_script:
  - phpenv config-rm xdebug.ini || true
  - cp .env.travis .env
  - mysql -e 'CREATE DATABASE yaktrack;'
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate

script: vendor/bin/phpunit
